CREATE DATABASE Eleicoes;
USE eleicoes;

CREATE TABLE eleicao (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(30) NOT NULL, dataInicio VARCHAR(30) NOT NULL, dataFim VARCHAR(30) NOT NULL);
CREATE TABLE cargo (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(30) NOT NULL, id_eleicao INT UNSIGNED NOT NULL, FOREIGN KEY(id_eleicao) REFERENCES Eleicao(id) ON DELETE CASCADE);
CREATE TABLE candidato (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(30) NOT NULL, nomeFoto VARCHAR(30) NOT NULL, id_cargo INT UNSIGNED NOT NULL, FOREIGN KEY(id_cargo) REFERENCES cargo(id) ON DELETE CASCADE);
CREATE TABLE eleitor (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(30) NOT NULL, cpf VARCHAR(30) NOT NULL, protocolo VARCHAR(19) NOT NULL, id_eleicao INT UNSIGNED NOT NULL, FOREIGN KEY(id_eleicao) REFERENCES Eleicao(id) ON DELETE CASCADE);
CREATE TABLE voto (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, id_eleicao INT UNSIGNED NOT NULL, id_cargo INT UNSIGNED NOT NULL, id_candidato INT UNSIGNED NOT NULL, FOREIGN KEY(id_eleicao) REFERENCES eleicao(id) ON DELETE CASCADE, FOREIGN KEY(id_cargo) REFERENCES cargo(id) ON DELETE CASCADE, FOREIGN KEY(id_candidato) REFERENCES candidato(id) ON DELETE CASCADE);

CREATE USER 'dbadmin'@'localhost' IDENTIFIED BY 'dataa';
GRANT ALL PRIVILEGES ON eleicoes.* TO 'dbadmin'@'localhost' IDENTIFIED BY 'dataa';
